### ISSUE TITLE
Installation difficulty

### ISSUE THREAD

**Issue by keflavich** [pcubillos/bibmanager#43]
I tried cloning and installing and immediately ran into:
```
 python setup.py install
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    import bibmanager as bibm
  File "/Users/adam/repos/bibmanager/bibmanager/__init__.py", line 7, in <module>
    from . import bib_manager
  File "/Users/adam/repos/bibmanager/bibmanager/bib_manager/__init__.py", line 4, in <module>
    from .bib_manager import *
  File "/Users/adam/repos/bibmanager/bibmanager/bib_manager/bib_manager.py", line 31, in <module>
    from prompt_toolkit.formatted_text import PygmentsTokens
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
```

Do I need a particular version of `prompt_toolkit`?

**Comment by pcubillos** [comment]
Yes you do, can you check that you have:
prompt_toolkit>=2.0.7
It's supposed to be on the requirements, maybe it's not picking that up.

**Comment by pcubillos** [comment]
I'm closing this since we agreed that it was an requirements incompatibility with your other projects.

Take a look at the FAQs, here's a recipe to install bibmanager in an isolated virtual environment, and then making it available out of it in your machine:
https://bibmanager.readthedocs.io/en/latest/faq.html#i-installed-bibmanager-while-being-in-a-virtual-environment-but-i-don-t-want-to-start-the-virtual-env-every-time-i-want-to-use-bibm
