### ISSUE TITLE
long term goals?

### ISSUE THREAD

**Issue by michaelaye** [pcubillos/bibmanager#48]
Was just wondering if, in the long term, this project could add the pdf management of the document for the bibtex reference as well? 
Would be fantastic, as it could potentially replace the half-working paperpile.com, Papers.app and ReadCube apps.
In connection with an editor plugin for searching the database, that's all I ever wanted from a reference manager. ;)

**Comment by pcubillos** [comment]
Hi Michael, this is what I have in mind:

- Yes, I'm already working on the PDF manager (last week I got an ADS-fetcher working :D ), and in general, I'm pretty sure I can get something working soon. It's more of a matter of me balancing work and other stuff.

- I really like the pluggins idea, it will be good to attract users. I'll give it a try, at last with vscode. But I'll need to learn stuff before I can make some progress. So that might take some more time.  Hopefully, there will be some external contributions now that I got some more exposure.

- I want to check sqlite3 or some other standard package designed for databases.
- A GUI is something else I have in mind that could be added. But that is a longer-term idea.

Thanks for all the interest and input, there are many Python things that I'm still learning, and this helps a lot.

**Comment by michaelaye** [comment]
if you don't want to keep this GH issue alive, you could create some projects in the GH Projects tab. That way contributors could get. an insight into the current short/mid/long term projects going on.

**Comment by michaelaye** [comment]
BTW, I just checked on sqlite and PDFs, I think. ppl recommend to just use the file system and store the paths to the PDF inside the database, not to store the actual PDF inside a sqlite. Also, I'm a fan of minimization, so as long as your pickle storage works, why change it. ;)

**Comment by pcubillos** [comment]
Hi @michaelaye,
PDF management is now enabled (including ADS fetching). Take a look at tag v1.2.0rc2:
https://pypi.org/project/bibmanager/1.2.0rc2/
https://bibmanager.readthedocs.io/en/v1.2.0rc2/

The database's home directory is settable, so you can put it in a Dropbox folder and work across multiple machines.

I'm moving the rest of these items into projects to close this issue.
